defmodule Aistorybook.Repo.Migrations.AddTextWidth do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:panels) do
      add :text_width, :bigint, null: false, default: 150
    end
  end

  def down do
    alter table(:panels) do
      remove :text_width
    end
  end
end
