defmodule Aistorybook.Repo.Migrations.ChangeDefaultFont do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:panels) do
      modify :font, :text, default: "Courier New"
    end
  end

  def down do
    alter table(:panels) do
      modify :font, :text, default: "Ariel"
    end
  end
end
