defmodule Aistorybook.Repo.Migrations.AddNotesToProject do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:projects) do
      add :notes, :map
    end
  end

  def down do
    alter table(:projects) do
      remove :notes
    end
  end
end
