defmodule Aistorybook.Repo.Migrations.ChangeNotesToString do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:projects) do
      modify :notes, :text
    end
  end

  def down do
    alter table(:projects) do
      modify :notes, :map
    end
  end
end
